.catalog:
  name: "Prometheus-ALM Stack"
  version: "1.0.5"
  description: "Prometheus Monitoring Solution for LAMP-81 Server"
  uuid: prometheus-1
  minimum_rancher_version: v0.56.0

alert-conf:
  scale: 1
graf-db:
  scale: 1
prometheus:
  scale: 1
  health_check:
    port: 9090
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 5000
    healthy_threshold: 2
grafana:
  scale: 1
  health_check:
    port: 3000
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 5000
    healthy_threshold: 2
prom-conf:
  scale: 1
alertmanager:
  scale: 1
  health_check:
    port: 9093
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 5000
    healthy_threshold: 2
rancher-api-integration:
  scale: 1
  health_check:
    port: 9010
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 5000
    healthy_threshold: 2
influxdb:
  scale: 1
  health_check:
    port: 8086
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 5000
    healthy_threshold: 2

